Server:
  port = 8080
Spring:
  datasource:
    name = news
    url =jdbc:mysql://localhost:3306/news
    username = root
    password = admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true