Server:
  port = 8080
Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
